UPDATE teams_master SET color_primary = '#610a0a' WHERE id = 290; -- 鹿島アントラーズ
UPDATE teams_master SET color_primary = '#f2dc4b' WHERE id = 281; -- 柏レイソル
UPDATE teams_master SET color_primary = '#cc0000' WHERE id = 287; -- 浦和レッズ
UPDATE teams_master SET color_primary = '#002c7c' WHERE id = 292; -- FC東京
UPDATE teams_master SET color_primary = '#2181e1' WHERE id = 294; -- 川崎フロンターレ
UPDATE teams_master SET color_primary = '#013dab' WHERE id = 296; -- 横浜F・マリノス
UPDATE teams_master SET color_primary = '#131798' WHERE id = 303; -- FC町田ゼルビア
UPDATE teams_master SET color_primary = '#0e42a2' WHERE id = 305; -- 水戸ホーリーホック
UPDATE teams_master SET color_primary = '#007038' WHERE id = 306; -- 東京ヴェルディ
UPDATE teams_master SET color_primary = '#ffe74a' WHERE id = 301; -- ジェフユナイテッド千葉
UPDATE teams_master SET color_primary = '#660099' WHERE id = 282; -- サンフレッチェ広島
UPDATE teams_master SET color_primary = '#ff7518' WHERE id = 283; -- 清水エスパルス
UPDATE teams_master SET color_primary = '#073489' WHERE id = 285; -- V・ファーレン長崎
UPDATE teams_master SET color_primary = '#d71515' WHERE id = 288; -- 名古屋グランパス
UPDATE teams_master SET color_primary = '#8c1515' WHERE id = 289; -- ヴィッセル神戸
UPDATE teams_master SET color_primary = '#ff56ab' WHERE id = 291; -- セレッソ大阪
UPDATE teams_master SET color_primary = '#0a3586' WHERE id = 293; -- ガンバ大阪
UPDATE teams_master SET color_primary = '#7503ae' WHERE id = 302; -- 京都サンガF.C.
UPDATE teams_master SET color_primary = '#ae2626' WHERE id = 310; -- ファジアーノ岡山
UPDATE teams_master SET color_primary = '#032159' WHERE id = 316; -- アビスパ福岡
